-- Create database
CREATE DATABASE IF NOT EXISTS car_rental;
USE car_rental;

-- Enum simulation in MySQL using ENUM type

-- User table
CREATE TABLE users (
    id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()), -- UUID auto-generated
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    role ENUM('USER','ADMIN') DEFAULT 'USER',
    licenseUrl VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Car table
CREATE TABLE cars (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    type ENUM('SEDAN','SUV','HATCHBACK','VAN','TRUCK') NOT NULL,
    fuelType ENUM('PETROL','DIESEL','ELECTRIC','HYBRID') NOT NULL,
    seats INT NOT NULL,
    pricePerDay FLOAT NOT NULL,
    imageUrl VARCHAR(255),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Booking table
CREATE TABLE bookings (
    id CHAR(36) NOT NULL PRIMARY KEY,
    userId CHAR(36) NOT NULL,
    carId CHAR(36) NOT NULL,
    startDate DATETIME NOT NULL,
    endDate DATETIME NOT NULL,
    status ENUM('PENDING','CONFIRMED','CANCELLED','COMPLETED') DEFAULT 'PENDING',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (carId) REFERENCES cars(id) ON DELETE CASCADE
);
